# Configuration du projet GitHub pour Le Circographe

# Milestones
milestones:
  - title: "Sprint 1 (10-15 mars)"
    description: "Premier sprint - Mise en place du projet et fondations frontend"
    due_on: "2024-03-15T23:59:59Z"
  - title: "Sprint 2 (17-22 mars)"
    description: "Deuxième sprint - Développement des fonctionnalités principales"
    due_on: "2024-03-22T23:59:59Z"
  - title: "Sprint 3 (23-28 mars)"
    description: "Troisième sprint - Finalisation du MVP"
    due_on: "2024-03-28T23:59:59Z"

# Labels
labels:
  # Types
  - name: "frontend"
    color: "0E8A16"
    description: "Tâches liées au frontend"
  - name: "backend"
    color: "1D76DB"
    description: "Tâches liées au backend"
  - name: "full-stack"
    color: "5319E7"
    description: "Tâches impliquant frontend et backend"
  - name: "documentation"
    color: "0075CA"
    description: "Tâches de documentation"
  - name: "tests"
    color: "FBCA04"
    description: "Tâches de tests"
  
  # Priorités
  - name: "priorité: haute"
    color: "D93F0B"
    description: "Tâches de haute priorité"
  - name: "priorité: moyenne"
    color: "FBCA04"
    description: "Tâches de priorité moyenne"
  - name: "priorité: basse"
    color: "0E8A16"
    description: "Tâches de priorité basse"
  
  # Domaines
  - name: "domaine: adhésion"
    color: "C5DEF5"
    description: "Tâches liées au domaine Adhésion"
  - name: "domaine: cotisation"
    color: "C5DEF5"
    description: "Tâches liées au domaine Cotisation"
  - name: "domaine: paiement"
    color: "C5DEF5"
    description: "Tâches liées au domaine Paiement"
  - name: "domaine: présence"
    color: "C5DEF5"
    description: "Tâches liées au domaine Présence"
  - name: "domaine: rôles"
    color: "C5DEF5"
    description: "Tâches liées au domaine Rôles"
  - name: "domaine: notification"
    color: "C5DEF5"
    description: "Tâches liées au domaine Notification"
  
  # Statuts
  - name: "statut: à faire"
    color: "D4C5F9"
    description: "Tâche à faire"
  - name: "statut: en cours"
    color: "FEF2C0"
    description: "Tâche en cours"
  - name: "statut: en revue"
    color: "BFDADC"
    description: "Tâche en attente de revue"
  - name: "statut: bloquée"
    color: "D93F0B"
    description: "Tâche bloquée"
  - name: "statut: terminée"
    color: "0E8A16"
    description: "Tâche terminée"

# Colonnes du projet
project:
  name: "Circographe MVP"
  columns:
    - name: "À faire"
      description: "Tâches à faire"
    - name: "En cours"
      description: "Tâches en cours de développement"
    - name: "En revue"
      description: "Tâches en attente de revue"
    - name: "Bloquées"
      description: "Tâches bloquées"
    - name: "Terminées"
      description: "Tâches terminées"

# Automatisations
automations:
  - trigger: "labeled"
    label: "statut: à faire"
    action: "move_to_column"
    column: "À faire"
  - trigger: "labeled"
    label: "statut: en cours"
    action: "move_to_column"
    column: "En cours"
  - trigger: "labeled"
    label: "statut: en revue"
    action: "move_to_column"
    column: "En revue"
  - trigger: "labeled"
    label: "statut: bloquée"
    action: "move_to_column"
    column: "Bloquées"
  - trigger: "labeled"
    label: "statut: terminée"
    action: "move_to_column"
    column: "Terminées" 