source "https://rubygems.org"
ruby "3.2.0"

gem "rails", "~> 8.0.1"
gem "sqlite3", "~> 1.4"
gem "puma", "~> 6.0"
gem "turbo-rails"
gem "stimulus-rails"
gem "tailwindcss-rails"
gem "flowbite-rails"
gem "image_processing" # Pour Active Storage et Pour prod storage

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
end 